---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - make install

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/